site_name: arxiv2025_abcd_link
nav:
  - Home: index.md

theme:
  name: material

plugins:
  - search
  - mkdocstrings:
      project_name: arxiv2025_abcd_link
      handlers:
        python:
          options:
            docstring_style: numpy